// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkcqzfidylmflqdibdik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrY3F6ZmlkeWxtZmxxZGliZGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjA2NzMsImV4cCI6MjA2NTgzNjY3M30.BRChrj2nobu233ibIIlYthMqfJmAvE_ndNCtxizqIJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);